spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&amp&useSSL=false&amp&serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: update



siteconfig:
  sites:
    - url: https://skillbox.ru
      name: skillbox
    - url: https://lenta.ru
      name: lenta
